### ISSUE TITLE
Error in React Native 0.71.11

### ISSUE THREAD

**Issue by dhdez-blife** [safaeean/react-native-scan-barcode#13]
```
info Opening the app on Android...
info JS server already running.
info Installing the app...
> Task :react-native-gradle-plugin:compileKotlin UP-TO-DATE
> Task :react-native-gradle-plugin:compileJava NO-SOURCE
> Task :react-native-gradle-plugin:pluginDescriptors UP-TO-DATE
> Task :react-native-gradle-plugin:processResources UP-TO-DATE
> Task :react-native-gradle-plugin:classes UP-TO-DATE
> Task :react-native-gradle-plugin:inspectClassesForKotlinIC UP-TO-DATE
> Task :react-native-gradle-plugin:jar UP-TO-DATE
5 actionable tasks: 5 up-to-date

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\blife\barcode\node_modules\react-native-scan-barcode\android\build.gradle' line: 16

* What went wrong:
A problem occurred evaluating project ':react-native-scan-barcode'.
> Could not find method compile() for arguments [com.google.zxing:core:3.2.1] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s

Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\blife\barcode\node_modules\react-native-scan-barcode\android\build.gradle' line: 16

* What went wrong:
A problem occurred evaluating project ':react-native-scan-barcode'.
> Could not find method compile() for arguments [com.google.zxing:core:3.2.1] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s

    at makeError (C:\blife\barcode\node_modules\execa\index.js:174:9)
    at C:\blife\barcode\node_modules\execa\index.js:278:16
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runOnAllDevices (C:\blife\barcode\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:82:7)
    at async Command.handleAction (C:\blife\barcode\node_modules\@react-native-community\cli\build\index.js:108:9)
info Run CLI with --verbose flag for more details.
```

**Comment by eliotmasset** [comment]
Hy, i have the same error, it occurs when version of gradle is greater than 7.0...

**Comment by Dev2927** [comment]
use 2.5.0 version. It will work and if it isn't give me again the screenshot

**Comment by mastahed** [comment]
it still occurs on version 3.1.7 with react native 0.72.7
